### ISSUE TITLE
超出宽度的文字显示省略号

### ISSUE THREAD

**Issue by Orange-J** [Orange-J/blogs#20]
```css
.ellipsis {
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
}
```
